with-expecter: true
outpkg: mock
mockname: "{{.InterfaceName}}"
filename: "{{.MockName}}.go"
packages:
    github.com/kiwicom/terraform-provider-montecarlo/monte_carlo/client:
        config:
          dir: "{{.InterfaceDir}}/mock"
        interfaces:
            MonteCarloClient:
              config:
                filename: "monte_carlo_client.go"
