name: Feature Request
description: Create a feature request to help us improve the Terraform Provider
title: "[Feature]: "
labels: ["feature", "triage"]
projects: []
assignees:
  - ndopj
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: request-details
    attributes:
      label: Feature Request Details
      description: Describe the new functionality you would like to see.
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Specify the acceptance criteria for the proposed feature.
  - type: dropdown
    id: Importance
    attributes:
      label: Importance of the feature
      options:
        - nice to have
        - must have
      default: 0
      description: |
        Any **Monte Carlo** functionality can be considered as a _must have_ importance. \
        In case of **Monte Carlo** functionalities feature request, the GitHub issues \
        are rather used to track which request should be solved first (based on age).
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: By submitting this issue, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
        - label: I have reviewed the documentation and other relevant resources.
          required: true
        - label: I have searched for similar issues in the repository.
          required: true
        - label: I have provided all the requested information.
          required: true
  - type: markdown
    attributes:
      value: |
        ---
        Thank you for contributing to our Terraform Provider repository and for taking the time to fill out this feature request!
