name: Terraform Provider Tests

on:
  workflow_call:
  pull_request:
      branches:
        - master

permissions:
  # Permission for checking out code
  contents: read

jobs:
  acceptance-tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          cache: true
          go-version-file: 'go.mod'
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.5.*'
          terraform_wrapper: false
      - run:
          go test -v ./... -coverprofile=coverage.out
        env:
          TF_ACC: '1'
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: ./coverage.out
